### ISSUE TITLE
`form` and `complete` commands should work for years 2012-2015

### ISSUE THREAD

**Issue by zrisher** [brandon-rhodes/luca#7]
Following from our discussion on #2, various form files need to be updated to work with all years 2013-2015.

**Comment by brandon-rhodes** [comment]
Alas — since I maintain this as a personal tool only, I lack the time to go back for those years and spend hours trying to get those old tax forms all working and getting computed correctly. While I would be open to contributions, I won't have the extra cycles to volunteer to ever go do all of those forms myself.
